import PDFDocument from 'pdfkit';
import { COLORS } from '../types';

export const PAGE = {
  width: 612,
  height: 792,
  margin: 50,
  contentWidth: 512,
  contentBottom: 742,
} as const;

export function createDocument(): InstanceType<typeof PDFDocument> {
  return new PDFDocument({
    size: 'letter',
    margin: PAGE.margin,
    bufferPages: true,
    info: {
      Title: 'Sales Report',
      Author: '@capsule-pro/sales-reporting',
      Creator: '@capsule-pro/sales-reporting',
    },
  });
}

export function collectBuffer(doc: InstanceType<typeof PDFDocument>): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}

export function drawHeader(
  doc: InstanceType<typeof PDFDocument>,
  companyName: string,
  reportTitle: string,
  dateRangeText: string
): number {
  const headerHeight = 70;

  doc.rect(0, 0, PAGE.width, headerHeight).fill(COLORS.navy);

  doc.fontSize(18).font('Helvetica-Bold').fillColor(COLORS.white)
    .text(companyName || 'Sales Report', PAGE.margin, 18, {
      width: PAGE.contentWidth,
      lineBreak: false,
    });

  doc.fontSize(10).font('Helvetica').fillColor('#B0C4DE')
    .text(`${reportTitle}  |  ${dateRangeText}`, PAGE.margin, 42, {
      width: PAGE.contentWidth,
      lineBreak: false,
    });

  const returnY = headerHeight + 20;
  doc.x = PAGE.margin;
  doc.y = returnY;
  return returnY;
}

export function drawPageFooter(doc: InstanceType<typeof PDFDocument>): void {
  const range = doc.bufferedPageRange();
  const pageCount = range.count;

  for (let i = 0; i < pageCount; i++) {
    doc.switchToPage(i);

    const savedBottom = (doc.page as any).margins.bottom;
    (doc.page as any).margins.bottom = 0;

    doc.moveTo(PAGE.margin, PAGE.height - 40)
      .lineTo(PAGE.width - PAGE.margin, PAGE.height - 40)
      .strokeColor(COLORS.border)
      .lineWidth(0.5)
      .stroke();

    doc.fontSize(7).font('Helvetica').fillColor(COLORS.lightText)
      .text(
        `Generated by @capsule-pro/sales-reporting`,
        PAGE.margin, PAGE.height - 32,
        { width: PAGE.contentWidth / 2, lineBreak: false }
      );

    doc.fontSize(7).font('Helvetica').fillColor(COLORS.lightText)
      .text(
        `Page ${i + 1} of ${pageCount}`,
        PAGE.width / 2, PAGE.height - 32,
        { width: PAGE.contentWidth / 2, align: 'right', lineBreak: false }
      );

    (doc.page as any).margins.bottom = savedBottom;
    doc.y = PAGE.margin;
  }
}

export function addPageBreak(doc: InstanceType<typeof PDFDocument>): number {
  doc.addPage();
  return PAGE.margin;
}
